import Router from '@koa/router';
import login from '../controller/login';
import register from '../controller/register';
import imgs from '../controller/imgs'
import chatList from '../controller/chatList';
import getMessage from '../controller/getMessage';
import getAllUsers from '../controller/getAllUsers';
import getUser from '../controller/getUser';
import getRequest from '../controller/getRequest';
import getReply from '../controller/getReply';
import getSelfInfo from '../controller/getSelfInfo';
import updateUserInfo from '../controller/updateUserInfo';
import updateHeadPorUrl from '../controller/updateHeadPorUrl';
import sendImgMessage from '../controller/sendImgMessage';
import getEmoji from '../controller/getEmoji';
const router = new Router();
router.post('/api/login', login);
router.post('/api/register', register);
router.post('/api/getMessage', getMessage);
router.post('/api/getAllUsers', getAllUsers);
router.post('/api/getUser', getUser);
router.post('/api/updateUserInfo', updateUserInfo);
router.post('/api/updateHeadPorUrl', updateHeadPorUrl);
router.post('/api/sendImgMessage', sendImgMessage);
router.get('/api/chatList', chatList);
router.get('/api/getRequest', getRequest);
router.get('/api/getReply', getReply);
router.get('/api/getSelfInfo', getSelfInfo);
router.get('/api/getEmoji', getEmoji);
router.get('/api/img/:id', imgs);
export default router;
